// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

// Generated from Cell.ts

export type Cell = 'empty' | 'player1' | 'player2';

// Generated from GameState.ts

export interface GameState {
  board: Array<Array<Cell>>;
  current_player: Player;
  genetic_params: GeneticParams;
}

// Generated from GeneticParams.ts

export interface GeneticParams {
  id: string;
  parent_ids: Array<string>;
  generation: number;
  win_score: number;
  loss_score: number;
  center_column_value: number;
  adjacent_center_value: number;
  outer_column_value: number;
  edge_column_value: number;
  row_height_weight: number;
  center_control_weight: number;
  piece_count_weight: number;
  threat_weight: number;
  mobility_weight: number;
  vertical_control_weight: number;
  horizontal_control_weight: number;
  defensive_weight: number;
}

// Generated from MLDiagnostics.ts

export interface MLDiagnostics {
  validMoves: Array<number>;
  moveEvaluations: Array<MLMoveEvaluation>;
  valueNetworkOutput: number;
  policyNetworkOutputs: Array<number>;
}

// Generated from MLMoveEvaluation.ts

export interface MLMoveEvaluation {
  column: number;
  score: number;
  moveType: string;
}

// Generated from MoveEvaluationWasm.ts

export interface MoveEvaluationWasm {
  column: number;
  score: number;
  moveType: string;
}

// Generated from Player.ts

export type Player = 'player1' | 'player2';

// Generated from WasmBestMoveResponse.ts

export interface WasmBestMoveResponse {
  move: number | null;
  evaluations: Array<MoveEvaluationWasm>;
  nodesEvaluated: number;
  transpositionHits: number;
}

// Generated from WasmMLResponse.ts

export interface WasmMLResponse {
  move: number | null;
  evaluation: number;
  thinking: string;
  diagnostics: MLDiagnostics;
}
