import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/lib/__tests__/setup.ts'],
    globals: true,
    css: false,
    testTimeout: 10000,
    hookTimeout: 10000,
    teardownTimeout: 5000,
    exclude: [
      'node_modules',
      '**/node_modules/**',
      '**/dist/**',
      '**/out/**',
      '**/e2e/**',
      '**/playwright/**',
      '**/.git/**',
      '**/coverage/**',
      '**/.turbo/**',
      '**/.vscode/**',
      '**/wasm/**',
      '**/pkg/**',
      '**/target/**',
      '**/build/**',
      '**/scripts/**',
      '**/public/**',
      '**/migrations/**',
      '**/docs/**',
      '**/test-db/**',
      '**/test/**',
      '**/__snapshots__/**',
      '**/*.d.ts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'src/lib/sound-effects.ts',
        'src/lib/types.ts',
        'node_modules/**',
        '**/node_modules/**',
        'src/lib/__tests__/**',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/*.d.ts',
        '**/*.config.*',
        'worker/**',
        'public/**',
        'migrations/**',
        'scripts/**',
        'docs/**',
        'e2e/**',
        'playwright/**',
        '**/coverage/**',
        '**/dist/**',
        '**/build/**',
        '**/target/**',
        '**/pkg/**',
        '**/wasm/**',
        '**/setup.ts',
        'src/main.tsx',
        'src/App.tsx',
        'src/components/**',
        'src/service-worker.ts',
        'src/components/**',
        'src/hooks/**',
        'src/worker.ts',
        'src/lib/ai.worker.ts',
        'src/lib/wasm-ai-service.ts',
        'src/lib/__tests__/wasm-ai-service.test.ts',
      ],
      include: ['src/**/*.ts', 'src/**/*.tsx', 'src/**/*.js', 'src/**/*.jsx'],
      thresholds: {
        statements: 70,
        branches: 60,
        functions: 70,
        lines: 70,
      },
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '/wasm': resolve(__dirname, './public/wasm'),
    },
  },
});
