name = "rowspire-main"
main = "src/worker.ts"
compatibility_date = "2026-07-13"

[assets]
directory = "./out/client"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[routes]]
pattern = "rowspire.tre.systems"
custom_domain = true

[[routes]]
pattern = "rowspire.com"
custom_domain = true

[[routes]]
pattern = "www.rowspire.com"
custom_domain = true

[[routes]]
pattern = "rowspire.net"
custom_domain = true

[[routes]]
pattern = "www.rowspire.net"
custom_domain = true

[[routes]]
pattern = "rowspire.org"
custom_domain = true

[[routes]]
pattern = "www.rowspire.org"
custom_domain = true

[[routes]]
pattern = "connect-4.tre.systems"
custom_domain = true
