#!/usr/bin/env bash
set -euo pipefail

echo "🦀 Generating Types from Rust..."
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT/worker"
cargo test --locked --test bindings_test --features wasm

echo "📦 Bundling bindings to frontend..."
DEST_FILE="$ROOT/src/lib/bindings.ts"
BINDINGS_DIR="bindings"

rm -rf "$ROOT/src/lib/bindings"

echo "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually." > "$DEST_FILE"

for f in "$BINDINGS_DIR"/*.ts; do
  echo "" >> "$DEST_FILE"
  echo "// Generated from $(basename "$f")" >> "$DEST_FILE"
  grep -v "^import" "$f" | grep -v "^//" >> "$DEST_FILE"
done

cd "$ROOT"
npx prettier --write "$DEST_FILE" >/dev/null

rm -rf "$ROOT/worker/$BINDINGS_DIR"

echo "✅ Types generated and bundled into $DEST_FILE!"
