#!/bin/bash
set -e

echo "🦀 Generating Types from Rust..."
cd worker
# Run the test that exports the bindings
cargo test --test bindings_test --features wasm

echo "📦 Bundling bindings to frontend..."
DEST_FILE="../src/lib/bindings.ts"
BINDINGS_DIR="bindings"

# Remove the old directory if it exists (since we are switching to a single file)
rm -rf ../src/lib/bindings

echo "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually." > "$DEST_FILE"

for f in "$BINDINGS_DIR"/*.ts; do
  echo "" >> "$DEST_FILE"
  echo "// Generated from $(basename "$f")" >> "$DEST_FILE"
  # Skip lines starting with 'import' (imports from other generated files)
  # Skip lines starting with '//' (comments, specifically the header generated by ts-rs)
  grep -v "^import" "$f" | grep -v "^//" >> "$DEST_FILE"
done

# Cleanup intermediate files
rm -rf "$BINDINGS_DIR"

echo "✅ Types generated and bundled into $DEST_FILE!"
